workspace = { members = ["abc300", "mysnippet", "abc201", "maximum-cup-2018"], exclude = [] }
[package]
name = "atcoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
