#!/bin/bash

# 引数の数をチェック
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
  echo "Usage: $0 [c|vc] <project_name>"
  exit 1
fi

# 引数の処理
if [ $# -eq 1 ]; then
  option="c"
  project_name=$1
else
  option=$1
  project_name=$2
fi

case $option in
  c)
    cd contest
    cargo compete new $project_name
    cd ..
    cargo member include contest/$project_name
    cd contest/$project_name
    ;;
  vc)
    cd virtual_contest
    cargo compete new $project_name
    cd ..
    cargo member include virtual_contest/$project_name
    cd virtual_contest/$project_name
    ;;
  *)
    echo "Invalid option: $option"
    echo "Usage: $0 [c|vc] <project_name>"
    exit 1
    ;;
esac

git add .
git commit -m "Add $project_name"
git push origin main
