#!/bin/sh

set -e  # コマンドが失敗したらスクリプトを即座に終了

cd mysnippet

cargo test

cargo snippet -t vscode | sed -r "s/\"prefix\"/\"scope\": \"rust\",\n    \"prefix\"/" > ../.vscode/cargo_snippet.code-snippets

cd ..

git add .
git commit -m "update snippet"
git push origin main
